/// Special actions that the key handler requests from the editor host.
#[derive(Default)]
pub struct KeyAction {
    pub save: bool,
    pub undo: bool,
    pub redo: bool,
    pub select_all: bool,
    pub cut: bool,
    pub copy: bool,
    pub paste: bool,
    pub delete_line: bool,
    pub duplicate_line: bool,
    pub move_line_up: bool,
    pub move_line_down: bool,
    pub goto_definition: bool,
    pub request_hover: bool,
    pub request_completion: bool,
    pub accept_completion: bool,
    pub dismiss_completion: bool,
    pub completion_up: bool,
    pub completion_down: bool,
    pub format_document: bool,
    pub rename_symbol: bool,
    pub code_actions: bool,
    pub document_symbols: bool,
    pub open_file_finder: bool,
    pub fold_current: bool,
    pub unfold_current: bool,
    pub fold_all: bool,
    pub unfold_all: bool,
    pub open_find: bool,
    pub open_find_replace: bool,
    pub find_references: bool,
    pub workspace_symbols: bool,
    pub project_search: bool,
    pub run_task: bool,
    pub add_cursor_next: bool,
    pub select_all_occurrences: bool,
    pub toggle_line_comment: bool,
    pub toggle_block_comment: bool,
    pub jump_to_matching_bracket: bool,
}
